#pragma once

#include <NGIN/Crypto/Algorithm.hpp>
#include <NGIN/Crypto/Asymmetric/Ed25519.hpp>
#include <NGIN/Crypto/Asymmetric/KeyPair.hpp>
#include <NGIN/Crypto/Asymmetric/KeyTypes.hpp>
#include <NGIN/Crypto/Asymmetric/PrivateKey.hpp>
#include <NGIN/Crypto/Asymmetric/PublicKey.hpp>
#include <NGIN/Crypto/Asymmetric/X25519.hpp>
#include <NGIN/Crypto/Backend/BackendCapabilities.hpp>
#include <NGIN/Crypto/Backend/BackendInfo.hpp>
#include <NGIN/Crypto/Backend/BackendOptions.hpp>
#include <NGIN/Crypto/Backend/CryptoContext.hpp>
#include <NGIN/Crypto/ByteBuffer.hpp>
#include <NGIN/Crypto/Concepts.hpp>
#include <NGIN/Crypto/Encoding/Base64.hpp>
#include <NGIN/Crypto/Encoding/Base64Url.hpp>
#include <NGIN/Crypto/Encoding/Hex.hpp>
#include <NGIN/Crypto/Errors/CryptoError.hpp>
#include <NGIN/Crypto/Hashing/Digest.hpp>
#include <NGIN/Crypto/Hashing/Hash.hpp>
#include <NGIN/Crypto/Hashing/HashAlgorithm.hpp>
#include <NGIN/Crypto/Kdf/Argon2id.hpp>
#include <NGIN/Crypto/Kdf/Hkdf.hpp>
#include <NGIN/Crypto/Kdf/KeyDerivation.hpp>
#include <NGIN/Crypto/Kdf/Pbkdf2.hpp>
#include <NGIN/Crypto/Mac/Hmac.hpp>
#include <NGIN/Crypto/Mac/HmacSha256.hpp>
#include <NGIN/Crypto/Mac/HmacSha512.hpp>
#include <NGIN/Crypto/Mac/Mac.hpp>
#include <NGIN/Crypto/Mac/MacAlgorithm.hpp>
#include <NGIN/Crypto/Memory/ConstantTime.hpp>
#include <NGIN/Crypto/Memory/Secret.hpp>
#include <NGIN/Crypto/Memory/SecretView.hpp>
#include <NGIN/Crypto/Memory/SecureBuffer.hpp>
#include <NGIN/Crypto/Memory/ZeroMemory.hpp>
#include <NGIN/Crypto/Random/EntropySource.hpp>
#include <NGIN/Crypto/Random/Random.hpp>
#include <NGIN/Crypto/Result.hpp>
#include <NGIN/Crypto/Signatures/Sign.hpp>
#include <NGIN/Crypto/Signatures/Signature.hpp>
#include <NGIN/Crypto/Signatures/Verify.hpp>
#include <NGIN/Crypto/Symmetric/Aead.hpp>
#include <NGIN/Crypto/Symmetric/AeadAlgorithm.hpp>
#include <NGIN/Crypto/Symmetric/AesGcm.hpp>
#include <NGIN/Crypto/Symmetric/ChaCha20Poly1305.hpp>
#include <NGIN/Crypto/Symmetric/XChaCha20Poly1305.hpp>
#include <NGIN/Crypto/Tokens/SecureToken.hpp>
#include <NGIN/Crypto/Tokens/TokenGenerator.hpp>
#include <NGIN/Crypto/Types.hpp>
