#pragma once
#include <NGIN/Containers/HashMap.hpp>
#include <NGIN/Text/String.hpp>
#include <NGIN/Text/Unicode.hpp>
#include <NGIN/Containers/Vector.hpp>
#include <NGIN/Defines.hpp>
#include <NGIN/Exceptions/Exception.hpp>
#include <NGIN/IO/DynamicLibrary.hpp>
#include <NGIN/Memory/AllocationHelpers.hpp>
#include <NGIN/Memory/AllocatorConcept.hpp>
#include <NGIN/Memory/FallbackAllocator.hpp>
#include <NGIN/Memory/HalfPointer.hpp>
#include <NGIN/Memory/LinearAllocator.hpp>
#include <NGIN/Memory/SystemAllocator.hpp>
#include <NGIN/Memory/TrackingAllocator.hpp>
#include <NGIN/Meta/EnumTraits.hpp>
#include <NGIN/Meta/FunctionTraits.hpp>
#include <NGIN/Meta/ReflectionIdentity.hpp>
#include <NGIN/Meta/SymbolId.hpp>
#include <NGIN/Meta/TypeId.hpp>
#include <NGIN/Meta/TypeTraits.hpp>
#include <NGIN/Primitives.hpp>
#include <NGIN/Serialization/Core/ParseDiagnostic.hpp>
#include <NGIN/Serialization/Core/ParseLimits.hpp>
#include <NGIN/Serialization/Core/ParseResources.hpp>
#include <NGIN/Serialization/Core/ParseScratch.hpp>
#include <NGIN/Serialization/Core/SourceBuffer.hpp>
#include <NGIN/Serialization/Core/SourceMap.hpp>
#include <NGIN/Serialization/Core/SourceSpan.hpp>
#include <NGIN/Serialization/JSON/JsonBuilder.hpp>
#include <NGIN/Serialization/JSON/JsonEventParser.hpp>
#include <NGIN/Serialization/JSON/JsonParser.hpp>
#include <NGIN/Serialization/JSON/JsonStreamWriter.hpp>
#include <NGIN/Serialization/JSON/JsonWriter.hpp>
#include <NGIN/Serialization/XML/XmlBuilder.hpp>
#include <NGIN/Serialization/XML/XmlEventParser.hpp>
#include <NGIN/Serialization/XML/XmlParser.hpp>
#include <NGIN/Serialization/XML/XmlStreamWriter.hpp>
#include <NGIN/Serialization/XML/XmlWriter.hpp>
#include <NGIN/Utilities/Any.hpp>
#include <NGIN/Utilities/Callable.hpp>
#include <NGIN/Utilities/Expected.hpp>
#include <NGIN/Utilities/LSBFlag.hpp>
#include <NGIN/Utilities/MSBFlag.hpp>
#include <NGIN/Utilities/Optional.hpp>
#include <NGIN/Utilities/SymbolTable.hpp>
#include <NGIN/Utilities/StringInterner.hpp>


//#include<NGIN / Benchmark.hpp>
#include <NGIN/Timer.hpp>
#include <NGIN/Units.hpp>
